apiVersion: apps/v1
kind: Deployment
metadata:
  name: fileReaderappdeploy
  labels:
    app: flask
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: fileReaderappdeploy
        image: filereader
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: "/data/certs"
          name: ca-certs
          readOnly: true
      volumes:
      - name: ca-certs
---
apiVersion: v1
kind: Service
metadata:
  name: appdeploy
  labels:
    app: FastAPIFileReader
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: flask
  selector:
    app: flask
  type: LoadBalancer